import re

BOTS = re.compile('|'.join([
    # list of regex' that match a Bot's user-agent
    r"""Abonti""",
    r"""AcoonBot""",
    r"""AhrefsBot""",
    r"""aiHitBot""",
    r"""Anonymouse""",
    r"""bingbot""",
    r"""Blekkobot""",
    r"""BLEXBot""",
    r"""CareerBot""",
    r"""CompSpyBot""",
    r"""[Cc]rawl(er|ing)""",  # generic
    r"""Dataprovider\sSite\sExplorer""",
    r"""DCPbot""",
    r"""discoverybot""",
    r"""dlvr\.it""",
    r"""DotBot""",
    r"""Embedly""",
    r"""Ezooms""",
    r"""Exabot""",
#    r"""\+http://www\.google\.com/bot\.html""",
    r"""Googlebot""",
    r"""heritrix""",
    r"""hrbot""",
    r"""HTTrack""",
    r"""iCjobs""",
    r"""IndexBot""",
    # r"""http://www.\infohelfer\.de""",
    r"""IstellaBot""",
    r"""KomodiaBot""",
    r"""librabot""",
    r"""Linguee\sBot""",
    r"""LinkpadBot""",
    r"""LinksCrawler""",
    r"""Lipperhey\sSEO\sService""",
    r"""LoadTimeBot""",
    r"""meanpathbot""",
    r"""Mail\.RU_Bot""",
    r"""matchbot""",
    r"""MJ12bot""",
    r"""MojeekBot""",
    r"""msnbot""",
    r"""NCBot""",
    r"""Nutch\sCrawler""",
    r"""OppO""",
    r"""PaperLiBot""",
    r"""ProCogBot""",
    r"""ProCogSEOBot""",
    r"""Scrapy""",
    r"""ScreenerBot""",
    r"""SearchmetricsBot""",
    r"""Semager""",
    r"""SemrushBot""",
    r"""SEOkicks""",
    r"""SeznamBot""",
    r"""Shelob""",
    r"""ShowyouBot""",
    r"""SISTRIX""",
    r"""Slurp""",
    r"""SnapPreviewBot""",
    r"""socialbm_bot""",
    r"""spbot""",
    r"""[Ss]pider""",  # generic
    r"""SSL Labs""",
    r"""Toplistbot""",
    r"""TweetmemeBot""",
    r"""UnwindFetchor""",
    r"""WebProcess/.*""",
    r"""Wotbox""",
    r"""yacybot""",
    r"""Yandex(Bot)?""",
    r"""zitebot"""
]))
